### ISSUE TITLE
Exported JSON doesn't seem to match what's expected

### ISSUE THREAD

**Issue by andrewshell** [logseq/publish#1]
I created a new Logseq graph then created a new page "Prompts" and linked to it from the daily pages.
I then exported the JSON.

However, there is no "page" key in the exported JSON (just version and blocks) so I'm getting an error in:
`src/utils.js (35:13) @ createUUIDToBlockMap` "TypeError: Cannot read property 'forEach' of undefined"

I've attached my JSON so you can see (had to upload with txt extension) and my graph folder.
[data.json](https://github.com/logseq/publish/files/6677445/data.txt)
[logseq.zip](https://github.com/logseq/publish/files/6677448/logseq.zip)

I'm using the Logseq desktop app (v0.1.9) on macOS 11.4

**Comment by andrewshell** [comment]
If publish needs to be updated to handle the blocks only format I'm happy to submit a PR, if Logseq is exporting things incorrectly then I'll leave it in your capable hands. :-)

**Comment by thezjy** [comment]
@andrewshell This project is undergoing heavy changes and I think the error is because of incompatibility between the code and the exported JSON. I just ran `yarn dev` with your data.json and it works fine. Can you try it?

**Comment by andrewshell** [comment]
Yes! It looks like it works now. Thank you.
