### ISSUE TITLE
Website seems to be down

### ISSUE THREAD

**Issue by Robinlovelace** [logseq/publish#3]
I tried here but found nothing: https://publish-kappa.vercel.app/

**Comment by thezjy** [comment]
Thanks for reporting. The demo address has been updated.

**Comment by Robinlovelace** [comment]
Thanks for the quick fix but I still this:

![image](https://user-images.githubusercontent.com/1825120/127637334-163d34ad-28ea-41c7-8219-7152b02603f7.png)

**Comment by Robinlovelace** [comment]
Aha OK https://logseq.github.io/publish-demo/
