### ISSUE TITLE
Logseq repo has no "assets" folder

### ISSUE THREAD

**Issue by zhouqimark** [logseq/publish#8]
Did I miss anything?

**Comment by pengx17** [comment]
Is the graph public? Can I take a look?

**Comment by zhouqimark** [comment]
Thanks for replying
1. I exported the entire graph as a `data.json` file, and make sure there is at least one page public
2.Here is the question: I copy the `assets` folder from my local directory as it is called 'graph' to the `public` folder. Did I do it in a wrong way?
3.Then I did exactly what the guide say: Run yarn && yarn dev to start the site locally.
4.Eventually, The browser showed the page's content was empty
There is a another problem. If I start the serve locally without any file changed, the pics in the `assets` folder could not be rendered.

**Comment by pengx17** [comment]
Sorry, I thought you were on pengx17/logseq-publish. logseq/publish is not being maintained right now.

**Comment by zhouqimark** [comment]
Oh thanks! That makes sense.
